### ISSUE TITLE
Localisation paths 404 with reqs resolver in place

### ISSUE THREAD

**Issue by dizzystuff** [xini/silverstripe-bundled-userforms#1]
I'm working on an element like ElementForm, but it is its own subclass of BaseElement (which applies the userform trait, etc). This means that I didn't have the `block_default_userforms_js: true` config setting in place initially.

Without that, the requirements all loaded up via `UserDefinedFormControllerExtension`, and in particular `getUserFormsValidatei18nCandidatePaths()` seems to be returning a set of invalid paths which then 404 on page load. I haven't changed any config yet AFAIK so it seems like this breaking out of the box is worth noting.

This is the console log screenshot, the requests that are generated and fail upon loading a page with this element/userform on it.

![sshot](https://github.com/xini/silverstripe-bundled-userforms/assets/576903/775d3bc8-fd60-49e4-a31e-59e95a319e90)

When I get the chance I'll have a proper dig into it.

**Comment by xini** [comment]
I know. The pronlem is that I have no way of telling which localisations exist. So I just load all of them and hope for the best.

**Comment by xini** [comment]
This module uses [silverstripe-requirements-resolver](https://github.com/xini/silverstripe-requirements-resolver) to load jquery and jquery-validate. I am inclined to change how silverstripe-requirements-resolver works, with a local frontend build for jquery and jquery-validate, including localisation scripts if available. That way, when this module calls `RequirementsResolver::get('jquery-validate')`, jquery-validate including all required localisation files are loaded. That would all then go into new major versions mentioned in #2. Thoughts?

**Comment by xini** [comment]
@dizzystuff  The question is whether this https://github.com/xini/silverstripe-requirements-resolver is still necessary. We built it because SS was so far behind in jQuery versions. Today they require the latest version for every build: https://github.com/silverstripe/silverstripe-userforms/blob/6/package.json#L31. 
The bundler could still be valuable to bundle all those individual language scripts etc, but maybe just bundling the prebuilt files from https://github.com/silverstripe/silverstripe-userforms/ without pulling them from a CDN via https://github.com/xini/silverstripe-requirements-resolver? Then this issue would be fixed because I know what files exist. Thoughts?

**Comment by dizzystuff** [comment]
Short version; yeah, I like that a lot. I agree https://github.com/xini/silverstripe-requirements-resolver can be removed here, and using the local files rather than a CDN will help stability.

**Comment by xini** [comment]
fixed in 3.0.0
